name: Env specific variables action
description: Make it easy to create specific environment related variables
author: elseu
branding:
  icon: "terminal"
  color: "#EE3324"
inputs:
  environment_name:
    description: Environment name
    required: true
  mode:
    description: Mode
    required: true
runs:
  using: docker
  image: Dockerfile
